/**
 * A component where an action is triggered
 * @packageDocumentation
 */
export enum ContextModule {
  aboutTheWork = "aboutTheWork",
  artistCard = "artistCard",
  artistHeader = "artistHeader",
  artistRecentlySold = "artistRecentlySold",
  artistsTab = "artistsTab",
  artistsToFollowRail = "artistsToFollowRail",
  artworkGrid = "artworkGrid",
  artworkImage = "artworkImage",
  artworkSidebar = "artworkSidebar",
  auctionSidebar = "auctionSidebar",
  auctionCail = "auctionCard",
  auctionRail = "auctionRail",
  auctionResults = "auctionResults",
  auctionsInfo = "auctionsInfo",
  bannerPopUp = "bannerPopUp",
  browseFair = "browseFair",
  categoryRail = "categoryRail",
  collectionDescription = "collectionDescription",
  collectionRail = "collectionRail",
  consignSubmissionFlow = "consignSubmissionFlow",
  currentShowsRail = "currentShowsRail",
  fairInfo = "fairInfo",
  fairsHeader = "fairsHeader",
  fairRail = "fairCard",
  featuredArtistsRail = "featuredArtistsRail",
  footer = "footer",
  geneHeader = "geneHeader",
  header = "header",
  intextTooltip = "intextTooltip",
  liveAuctionsRail = "liveAuctionsRail",
  mainCarousel = "mainCarousel",
  minimalCTABanner = "minimalCTABanner",
  newWorksByArtistsYouFollowRail = "newWorksByArtistsYouFollowRail",
  otherWorksByArtistRail = "otherWorksByArtistRail",
  otherWorksFromPartnerRail = "otherWorksFromPartnerRail",
  otherWorksFromShowRail = "otherWorksFromShowRail",
  otherWorksInAuctionRail = "otherWorksInAuctionRail",
  partnerHeader = "partnerHeader",
  pastFairs = "pastFairs",
  popularArtistsRail = "popularArtistsRail",
  popUpModal = "popUpModal",
  recentlySavedRail = "recentlySavedRail",
  recentlyViewedRail = "recentlyViewedRail",
  recommendedArtistsRail = "recommendedArtistsRail",
  recommendedWorksForYouRail = "recommendedWorksForYouRail",
  relatedArtistsRail = "relatedArtistsRail",
  relatedWorksRail = "relatedWorksRail",
  saveWorksCTA = "saveWorksCTA",
  showHeader = "showHeader",
  showInfo = "showInfo",
  similarToWorksYouSavedRail = "similarToWorksYouSavedRail"
  similarToWorksYouViewedRail = "similarToWorksYouViewedRail"
  tagHeader = "tagHeader",
  trendingArtistsRail = "trendingArtistsRail",
  worksByPopularArtistsRail = "worksByPopularArtistsRail",
  worksForSaleRail = "worksForSaleRail"
}
